random_seed: 42
num_of_tasks: 40
ratio: 0.5
num_of_cores: 16
core_utilization: 0.75
periods: [10, 20, 40, 50, 100,200, 400, 500, 1000]
#periods: [10, 20, 40, 50, 100, 200]
mu_range: [0.3, 0.5]
overrun_percentage: 0.5
error_rate: 0.0
reliability: 0.9999999
assignment_policy: "FFD"
scheduling_policy: "EDF-VD"